import {
  CountryCode,
  LanguageCode,
  CallMode,
  PaymentProvider,
  type Country,
} from "@/lib/types";

export const COUNTRIES: Record<CountryCode, Country> = {
  [CountryCode.CD]: {
    code: CountryCode.CD,
    name: "République Démocratique du Congo",
    nameLocal: "Republiki ya Kongo Demokratiki",
    flag: "🇨🇩",
    currency: "CDF",
    phonePrefix: "+243",
    languages: [LanguageCode.FR, LanguageCode.LN, LanguageCode.SW, LanguageCode.KG, LanguageCode.LU],
    cities: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Goma", "Bukavu", "Kisangani", "Kananga", "Kolwezi"],
    payments: [PaymentProvider.MPESA, PaymentProvider.AIRTEL_MONEY, PaymentProvider.ORANGE_MONEY],
    modes: [CallMode.MBOKA, CallMode.LINGALA, CallMode.SERIEUX, CallMode.DIASPORA, CallMode.MONDE, CallMode.NUIT, CallMode.RESPECT],
    safetyLevel: 4,
    marketingTone: "pride",
    localTexts: {
      tagline: "Voix du Congo. Cœur ouvert.",
      cta: "Trouve une voix maintenant",
      waitingMessage: "On cherche une voix pour toi à Kinshasa…",
      matchedMessage: "Voix trouvée ! L'appel commence.",
      endMessage: "Belle rencontre vocale. Le Congo connecte.",
      safetyReminder: "Ton numéro reste caché. Toujours.",
    },
    startingPrice: 500, // CDF
    matchingRules: {
      requireSameCountry: false,
      ageRange: [18, 65],
    },
    isDiaspora: false,
  },

  [CountryCode.CG]: {
    code: CountryCode.CG,
    name: "République du Congo",
    nameLocal: "Republiki ya Kongo",
    flag: "🇨🇬",
    currency: "XAF",
    phonePrefix: "+242",
    languages: [LanguageCode.FR, LanguageCode.LN, LanguageCode.KG],
    cities: ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Impfondo", "Ouesso"],
    payments: [PaymentProvider.AIRTEL_MONEY, PaymentProvider.MTN_MONEY, PaymentProvider.ORANGE_MONEY],
    modes: [CallMode.MBOKA, CallMode.LINGALA, CallMode.SERIEUX, CallMode.MONDE, CallMode.NUIT, CallMode.RESPECT],
    safetyLevel: 4,
    marketingTone: "warmth",
    localTexts: {
      tagline: "Congo-Brazza parle. Le monde écoute.",
      cta: "Commence ta rencontre vocale",
      waitingMessage: "Recherche d'une voix de Brazzaville…",
      matchedMessage: "Connexion établie. Parle librement.",
      endMessage: "Merci pour cette belle voix. À bientôt.",
      safetyReminder: "Numéro protégé. Conversations sécurisées.",
    },
    startingPrice: 200, // XAF
    matchingRules: {
      requireSameCountry: false,
      ageRange: [18, 65],
    },
    isDiaspora: false,
  },

  [CountryCode.FR]: {
    code: CountryCode.FR,
    name: "France",
    nameLocal: "France",
    flag: "🇫🇷",
    currency: "EUR",
    phonePrefix: "+33",
    languages: [LanguageCode.FR, LanguageCode.LN],
    cities: ["Paris", "Lyon", "Marseille", "Bordeaux", "Toulouse", "Strasbourg", "Nantes", "Lille"],
    payments: [PaymentProvider.STRIPE, PaymentProvider.PAYPAL, PaymentProvider.PAYLIB],
    modes: [CallMode.DIASPORA, CallMode.LINGALA, CallMode.SERIEUX, CallMode.MONDE, CallMode.NUIT, CallMode.RESPECT],
    safetyLevel: 5,
    marketingTone: "trust",
    localTexts: {
      tagline: "La diaspora Congo en France. Une voix vers chez toi.",
      cta: "Retrouve les voix du Congo",
      waitingMessage: "Connexion en cours entre Paris et Kinshasa…",
      matchedMessage: "Voix connectée ! Tu es près de chez toi.",
      endMessage: "Beau voyage vocal. Jusqu'à la prochaine.",
      safetyReminder: "Même en diaspora, ton numéro reste protégé.",
    },
    startingPrice: 1.99, // EUR
    matchingRules: {
      prioritizeDiaspora: true,
      ageRange: [18, 70],
    },
    isDiaspora: true,
    homelandCodes: [CountryCode.CD, CountryCode.CG],
  },

  [CountryCode.BE]: {
    code: CountryCode.BE,
    name: "Belgique",
    nameLocal: "België / Belgique",
    flag: "🇧🇪",
    currency: "EUR",
    phonePrefix: "+32",
    languages: [LanguageCode.FR, LanguageCode.LN],
    cities: ["Bruxelles", "Liège", "Charleroi", "Gand", "Anvers", "Namur"],
    payments: [PaymentProvider.STRIPE, PaymentProvider.PAYPAL, PaymentProvider.PAYLIB],
    modes: [CallMode.DIASPORA, CallMode.LINGALA, CallMode.SERIEUX, CallMode.MONDE, CallMode.NUIT, CallMode.RESPECT],
    safetyLevel: 5,
    marketingTone: "trust",
    localTexts: {
      tagline: "Bruxelles-Kinshasa. Voix qui voyagent.",
      cta: "Parle avec le Congo",
      waitingMessage: "Connexion Bruxelles–Congo en cours…",
      matchedMessage: "Voix du Congo trouvée ! Parle.",
      endMessage: "Belle connexion diaspora. Reviens.",
      safetyReminder: "Protection totale. Numéro jamais partagé.",
    },
    startingPrice: 1.99, // EUR
    matchingRules: {
      prioritizeDiaspora: true,
      ageRange: [18, 70],
    },
    isDiaspora: true,
    homelandCodes: [CountryCode.CD, CountryCode.CG],
  },

  [CountryCode.CA]: {
    code: CountryCode.CA,
    name: "Canada",
    nameLocal: "Canada",
    flag: "🇨🇦",
    currency: "CAD",
    phonePrefix: "+1",
    languages: [LanguageCode.FR, LanguageCode.EN, LanguageCode.LN],
    cities: ["Montréal", "Toronto", "Ottawa", "Vancouver", "Québec", "Calgary"],
    payments: [PaymentProvider.STRIPE, PaymentProvider.PAYPAL, PaymentProvider.INTERAC],
    modes: [CallMode.DIASPORA, CallMode.LINGALA, CallMode.SERIEUX, CallMode.MONDE, CallMode.NUIT, CallMode.RESPECT],
    safetyLevel: 5,
    marketingTone: "aspiration",
    localTexts: {
      tagline: "De Montréal au Congo. La voix qui rapproche.",
      cta: "Retrouve les tiens",
      waitingMessage: "Connexion transatlantique en cours…",
      matchedMessage: "Voix connectée ! Bon voyage vocal.",
      endMessage: "Distance zéro entre les voix. Merci.",
      safetyReminder: "Au Canada comme au Congo, ton numéro est protégé.",
    },
    startingPrice: 2.49, // CAD
    matchingRules: {
      prioritizeDiaspora: true,
      ageRange: [18, 70],
    },
    isDiaspora: true,
    homelandCodes: [CountryCode.CD, CountryCode.CG],
  },

  [CountryCode.CI]: {
    code: CountryCode.CI,
    name: "Côte d'Ivoire",
    nameLocal: "Côte d'Ivoire",
    flag: "🇨🇮",
    currency: "XOF",
    phonePrefix: "+225",
    languages: [LanguageCode.FR],
    cities: ["Abidjan", "Yamoussoukro", "Bouaké", "San-Pédro", "Daloa", "Korhogo"],
    payments: [PaymentProvider.ORANGE_MONEY, PaymentProvider.MTN_MONEY, PaymentProvider.WAVE],
    modes: [CallMode.MBOKA, CallMode.SERIEUX, CallMode.MONDE, CallMode.NUIT, CallMode.RESPECT],
    safetyLevel: 4,
    marketingTone: "warmth",
    localTexts: {
      tagline: "Abidjan se connecte. La voix sans frontières.",
      cta: "Rencontre une voix d'Afrique",
      waitingMessage: "Recherche en cours à Abidjan…",
      matchedMessage: "Voix trouvée ! C'est parti.",
      endMessage: "Belle rencontre africaine. À bientôt.",
      safetyReminder: "Ton numéro, c'est sacré. On le garde pour toi.",
    },
    startingPrice: 200, // XOF
    matchingRules: {
      requireSameCountry: false,
      ageRange: [18, 60],
    },
    isDiaspora: false,
  },

  [CountryCode.CM]: {
    code: CountryCode.CM,
    name: "Cameroun",
    nameLocal: "Cameroun / Cameroon",
    flag: "🇨🇲",
    currency: "XAF",
    phonePrefix: "+237",
    languages: [LanguageCode.FR, LanguageCode.EN],
    cities: ["Douala", "Yaoundé", "Garoua", "Bamenda", "Bafoussam", "Ngaoundéré"],
    payments: [PaymentProvider.MTN_MONEY, PaymentProvider.ORANGE_MONEY],
    modes: [CallMode.MBOKA, CallMode.SERIEUX, CallMode.MONDE, CallMode.NUIT, CallMode.RESPECT],
    safetyLevel: 4,
    marketingTone: "pride",
    localTexts: {
      tagline: "Le Cameroun parle. Le monde entend.",
      cta: "Lance ton appel vocal",
      waitingMessage: "Connexion en cours sur Douala…",
      matchedMessage: "Voix camerounaise connectée !",
      endMessage: "Belle expérience. Le Cameroun connecte.",
      safetyReminder: "Anonymat garanti. Numéro invisible.",
    },
    startingPrice: 200, // XAF
    matchingRules: {
      requireSameCountry: false,
      ageRange: [18, 60],
    },
    isDiaspora: false,
  },

  [CountryCode.SN]: {
    code: CountryCode.SN,
    name: "Sénégal",
    nameLocal: "Sénégal",
    flag: "🇸🇳",
    currency: "XOF",
    phonePrefix: "+221",
    languages: [LanguageCode.FR],
    cities: ["Dakar", "Thiès", "Saint-Louis", "Ziguinchor", "Kaolack", "Mbour"],
    payments: [PaymentProvider.ORANGE_MONEY, PaymentProvider.WAVE, PaymentProvider.PAYPAL],
    modes: [CallMode.MBOKA, CallMode.SERIEUX, CallMode.MONDE, CallMode.NUIT, CallMode.RESPECT],
    safetyLevel: 5,
    marketingTone: "trust",
    localTexts: {
      tagline: "Dakar à l'écoute. Voix de l'Afrique.",
      cta: "Rencontre une voix maintenant",
      waitingMessage: "Connexion en cours à Dakar…",
      matchedMessage: "Voix trouvée. C'est beau.",
      endMessage: "Merci Dakar. Belle rencontre.",
      safetyReminder: "Téranga numérique : ton numéro est protégé.",
    },
    startingPrice: 200, // XOF
    matchingRules: {
      requireSameCountry: false,
      ageRange: [18, 65],
    },
    isDiaspora: false,
  },
};

export const COUNTRIES_LIST = Object.values(COUNTRIES);
